name: drip
description: "DRIP — Real Drink Specials Near You."
publish_to: 'none'
version: 1.0.10+11   # ← BIG bump so Codemagic treats it as brand new

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.1.0
  share_plus: ^10.0.0
  google_maps_flutter: ^2.12.3
  url_launcher: ^6.3.0
  speech_to_text: ^7.3.0
  geolocator: ^13.0.0
  http: ^1.2.2
  shared_preferences: ^2.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/splash.png
    - assets/greetings/
    - assets/smoothie_button.png
    - assets/coffee_button.png
    - assets/party_button.png
    - assets/instant_alerts.png
    - assets/selfie_share.jpg
    - assets/family_mode_button.png